// livro-clientes/livros-react/src/LivroDados.js
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import ControleLivros from './controle/ControleLivros';
import ControleEditora from './controle/ControleEditora';
import './App.css';

const controleLivro = new ControleLivros();
const controleEditora = new ControleEditora();

const LivroDados = props => {
    const opcoes = controleEditora.getEditoras();
    const [titulo, setTitulo] = useState("");
    const [resumo, setResumo] = useState("");
    const [autores, setAutores] = useState("");
    const [codEditora, setCodEditora] = useState(opcoes[0].value);
    const navigate = useNavigate();

    const tratarCombo = (event) => {
        const numerointeiro = parseInt(event.target.value);
        setCodEditora(numerointeiro);
    };

    const incluir = (event) => {
        event.preventDefault();
        const livro = {
          codigo: "",
          codEditora: codEditora,
          titulo: titulo,
          resumo: resumo,
          autores: autores.split("\n")
        };
        controleLivro.incluir(livro)
          .then(() => navigate("/"));
    };

    return (
        <main className='container-fluid'>
            <h1>Dados do Livro</h1>
            <form onSubmit={incluir}>
                <div className='form-group'>
                    <label htmlFor='title'>Título</label>
                    <input className='form-control' id='title' type='text' value={titulo}onChange= {(temp) => setTitulo(temp.target.value)}/>
                    <label className='mt-2' htmlFor='summary'>Resumo</label>
                    <textarea className='form-control' id='summary' rows="3" value={resumo}onChange=   {(temp) => setResumo(temp.target.value)}/>
                    <label className='mt-2' htmlFor='publisher'>Editora</label>
                    <select  className='form-control' id='publisher' value={codEditora}onChange= {tratarCombo}>
                        {opcoes.map((items) => (<option key={items.codEditora} value={items.codEditora}>{items.nome}</option>))}
                    </select>
                    <label className='mt-2' htmlFor='authors'>Autores</label>
                    <textarea className='form-control' id='authors' rows="3" value={autores}   onChange={(temp) => setAutores(temp.target.value)}/>
                    <button className='btn btn-primary mt-2' type='submit'>Salvar Livro</button>
                </div>
            </form>
        </main>
    )
};

export default LivroDados;

// livro-clientes/livros-angular/src/app/livro-dados/livro-dados.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import Editora from '../editora';
import Livro from '../livro';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';

@Component({
  selector: 'app-livro-dados',
  templateUrl: './livro-dados.component.html',
  styleUrl: './livro-dados.component.css'
})

export class LivroDadosComponent implements OnInit {
livro: Livro;
autoresForm: string = "";
editoras: Array<Editora> = [];
tempEditora: number = 0;

constructor (private servEditora: ControleEditoraService, private servLivros: ControleLivrosService, private router: Router) {
  this.livro = new Livro ("0", 0, "", "", [])
}

ngOnInit(): void {
  this.editoras = this.servEditora.getEditoras();
}

incluir = async () => {
  this.livro.autores = this.autoresForm.split('\n');
  await this.servLivros.incluir(this.livro);
  this.livro.codEditora = Number(this.tempEditora);
  this.router.navigateByUrl("/lista");
}
}
<main class="container-fluid" id="comp2">
    <h1>Dados do Livro</h1>
    <form (submit)="incluir()" ngNativeValidate>
        <div class="form-group">
            <label for="titulo">Título</label>
            <input class="form-control" id="titulo" type="text" name="titulo" required [(ngModel)]="livro.titulo"/>
            <label class="mt-2" for="resumo">Resumo</label>
            <textarea class="form-control" id="resumo" rows="3" name="resumo" [(ngModel)]="livro.resumo"></textarea>
            <label class="mt-2" for="editora">Editora</label>
            <select class="form-control" id="editora" name="editora" required [(ngModel)]="tempEditora">
                <option *ngFor="let edit of editoras" [value]="edit.codEditora">{{edit.nome}}</option>
            </select>
            <label class="mt-2" for="autores">Autores</label>
            <textarea class="form-control" id="autores" rows="3" name="autores" [(ngModel)]="autoresForm"></textarea>
            <button class="btn btn-primary mt-2" type="submit">Salvar Dados</button>
        </div>
    </form>
</main>
