// livro-clientes/livros-angular/src/app/livro-lista/livro-lista.component.ts
import { Component, OnInit } from '@angular/core';
import Editora from '../editora';
import Livro from '../livro';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';

@Component({
  selector: 'app-livro-lista',
  templateUrl: './livro-lista.component.html',
  styleUrl: './livro-lista.component.css'
})

export class LivroListaComponent implements OnInit{
  editoras: Array<Editora> = [];
  livros: Array<Livro> = [];

  constructor (private servEditora: ControleEditoraService, private servLivros: ControleLivrosService) {
    this.servEditora = servEditora;
    this.servLivros = servLivros;
  }

  async ngOnInit() {
    this.editoras = this.servEditora.getEditoras();
    this.livros = await this.servLivros.obterLivros();
  }

  excluir(codigo: string): void {
    this.servLivros.excluir(codigo)
      .then(() => this.servLivros.obterLivros())
      .then(livros => this.livros = livros);
  }

  obterNome = (codEditora: number): string => {
    return this.servEditora.getNomeEditora(codEditora);
  }
}
<main class="container-fluid" id="comp1">
    <h1>Catálogo de Livros</h1>
    <table class="table" id="livroTable">
        <thead class="table-dark">
            <tr>
                <th class="col-2">Título</th>
                <th class="col-6">Resumo</th>
                <th class="col-2">Autores</th>
                <th class="col-2">Editora</th>
            </tr>
        </thead>
        <tbody>
            <tr *ngFor="let item of livros">
                <td>
                    {{item.titulo}}<br>
                    <button class="btn btn-danger btn-sm" type="button" (click)="excluir(item.codigo)">Excluir</button>
                </td>
                <td class="textResumo">{{item.resumo}}</td>
                <td>
                    <ul>
                        <li *ngFor="let autor of item.autores">{{autor}}</li>
                    </ul>
                </td>
                <td>{{obterNome(item.codEditora)}}</td>
            </tr>
        </tbody>
    </table>
</main>

// livro-clientes/livros-next/pages/LivroLista.tsx
import Head from 'next/head';
import { useState, useEffect } from 'react';
import { Menu } from '../componentes/Menu';
import Livro from '../classes/modelo/Livros';
import { LinhaLivro } from '../componentes/LinhaLivro';
import 'bootstrap/dist/css/bootstrap.css';
import type { NextPage } from 'next';
import ControleLivros from '@/classes/controle/ControleLivros';
import {router} from "next/client";
import ControleEditora from '@/classes/controle/ControleEditora';

const baseURL = "http://localhost:3030/livros"

const LivroLista: NextPage = () => {
    const [livros, setLivros] = useState<Array<Livro>>([])
    const [carregado, setCarregado] = useState(false);


    const obterLivros = async () => {
        return await fetch(baseURL)
            .then((resposta) => resposta.json())
            .then((resposta) => resposta);
    }
    const excluirLivro = async (codigo: string) => {
        setCarregado(false);
        await ControleLivros.excluir(codigo)
        setLivros(await ControleLivros.obterLivros());
        setCarregado(true);

    }

    useEffect(() => {
        const carregaLivros = async () => {
            setLivros(await ControleLivros.obterLivros());
            setCarregado(true)
            return livros;
        };

        carregaLivros();
    }, []);

        return (
            <div>
                <Head>
                    <title>Catálogo de Livros</title>
                </Head>
                <Menu/>
                <main>
                    <div className="container-fluid">
                        <h1>Catálogo de Livros</h1>
                        <table className='table'>
                            <thead>
                                <tr className='table-dark'>
                                    <th className='col-2'>Título</th>
                                    <th className='col-4'>Resumo</th>
                                    <th className='col-2'>Editora</th>
                                    <th className='col-2'>Autores</th>
                                </tr>
                            </thead>
                            <tbody>
                            {livros.map((livro, index) => (<LinhaLivro key={index} livro={livro} excluir={excluirLivro}/>))}
                            </tbody>
                        </table>
                    </div>
                </main>
            </div>
        )
}

export default LivroLista
