// livro-clientes/livros-angular/src/app/livro-lista/livro-lista.component.ts
import { Component, OnInit } from '@angular/core';
import Editora from '../editora';
import Livro from '../livro';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';

@Component({
  selector: 'app-livro-lista',
  templateUrl: './livro-lista.component.html',
  styleUrl: './livro-lista.component.css'
})

export class LivroListaComponent implements OnInit{
  editoras: Array<Editora> = [];
  livros: Array<Livro> = [];

  constructor (private servEditora: ControleEditoraService, private servLivros: ControleLivrosService) {
    this.servEditora = servEditora;
    this.servLivros = servLivros;
  }

  async ngOnInit() {
    this.editoras = this.servEditora.getEditoras();
    this.livros = await this.servLivros.obterLivros();
  }

  excluir(codigo: string): void {
    this.servLivros.excluir(codigo)
      .then(() => this.servLivros.obterLivros())
      .then(livros => this.livros = livros);
  }

  obterNome = (codEditora: number): string => {
    return this.servEditora.getNomeEditora(codEditora);
  }
}
<main class="container-fluid" id="comp1">
    <h1>Catálogo de Livros</h1>
    <table class="table" id="livroTable">
        <thead class="table-dark">
            <tr>
                <th class="col-2">Título</th>
                <th class="col-6">Resumo</th>
                <th class="col-2">Autores</th>
                <th class="col-2">Editora</th>
            </tr>
        </thead>
        <tbody>
            <tr *ngFor="let item of livros">
                <td>
                    {{item.titulo}}<br>
                    <button class="btn btn-danger btn-sm" type="button" (click)="excluir(item.codigo)">Excluir</button>
                </td>
                <td class="textResumo">{{item.resumo}}</td>
                <td>
                    <ul>
                        <li *ngFor="let autor of item.autores">{{autor}}</li>
                    </ul>
                </td>
                <td>{{obterNome(item.codEditora)}}</td>
            </tr>
        </tbody>
    </table>
</main>

// livro-clientes/livros-react/src/LivroLista.js
import {useState, useEffect} from 'react';
import ControleEditora from './controle/ControleEditora';
import ControleLivros from './controle/ControleLivros';

const controleEditora = new ControleEditora();
const controleLivros = new ControleLivros();

const LinhaLivro = (props) => {
    const {livro, excluir} = props;
    const nomeEditora = controleEditora.getNomeEditora;
    
    return (
        <tr>
            <td>
                <p>{livro.titulo}</p>
                <button className='btn btn-danger btn-sm' type='button' onClick={() => excluir(livro.codigo)}>Excluir</button>
            </td>
            <td>
                {livro.resumo}
            </td>
            <td>
                {nomeEditora(livro.codEditora)}
            </td>
            <td>
                <ul>
                    {livro.autores.map((autor, index) => (<li key={index}>{autor}</li>))}
                </ul>
            </td>
        </tr>
    );
};

const LivroLista = () => {
    const [livros, setLivros] = useState([]);
    const [carregado, setCarregado] = useState(false);
    useEffect( () => {
        document.title = "Lista de Livros";
        controleLivros.obterLivros().then((livros)=>{
            setLivros(livros);
            setCarregado(true);
        })
            .catch((error) => {
                console.error("Erro ao Carregar os livros:", error);
                setCarregado(true);
            });

    }, []);

    const excluirlivro = (codigo) => {
        setCarregado(false);
        controleLivros.excluir(codigo).then(()=>{
            controleLivros.obterLivros().then((livros)=>{
                setLivros(livros)
            })
        })
        setCarregado(true);
    };

    return (
        <main className='container-fluid px-5 mt-1'>
            <h1>Catálogo de Livros</h1>
            <table className='table'>
                <thead>
                    <tr className='table-dark'>
                        <th className='col-2'>Título</th>
                        <th className='col-4'>Resumo</th>
                        <th className='col-2'>Editora</th>
                        <th className='col-2'>Autores</th>
                    </tr>
                    </thead>
                    <tbody>
                        {livros.map(livro => (
                            <LinhaLivro
                            key={livro.codigo}
                            livro={livro}
                            excluir={excluirlivro}
                            getNomeEditora={controleEditora.getNomeEditora}
                            />
                        ))}
                    </tbody>
            </table>
        </main>
    )
};

export default LivroLista
